### ISSUE TITLE
Accessing html files in python

### ISSUE THREAD

**Issue by VedantMadane** [sanskrit/sanskrit-documents-dump#2]
Thanks for making sanskrit-documents.org available offline.

Is there a way to access contents of any of the html documents without using BeautifulSoup?

**Comment by vvasuki** [comment]
There is a markdown dump at https://github.com/sanskrit/raw_etexts/tree/master/mixed/sandocs-dump-markdown - maybe you can access it directly there. 

PS: please don't host that content in an alternative user-facing site - the maintainer of that site may get upset!

**Comment by VedantMadane** [comment]
Thanks!
